[tool.pymarkdown]
# plugins.no-inline-html.enabled = false
# plugins.line-length.enabled = false
plugins.line-length.line_length = 92
# plugins.line-length.code_block_line_length = 92
# plugins.md033.allowed_elements = "p,kbd"
